"""Public application-service facade."""

from klausurbotpro.application.controller_design_workflow import (
    ControllerDesignCandidate,
    ControllerDesignCandidateStatus,
    ControllerDesignInputDraft,
    ControllerDesignMethod,
    ControllerDesignOutcomeDecision,
    ControllerDesignResult,
    ControllerDesignWorkflowService,
    ControllerType,
    controller_design_candidate_status_text,
    controller_design_method_text,
    decide_p_phase_margin_outcome,
)
from klausurbotpro.application.frequency_domain_request_factory import (
    FrequencyDomainInputDraft,
    FrequencyDomainRequestCreationResult,
    FrequencyDomainRequestFactory,
    FrequencyDomainRequestFieldError,
)
from klausurbotpro.application.frequency_domain_singularity_refinement import (
    FrequencyDomainSingularityRefinementPlan,
    FrequencyDomainSingularityRefinementPlanner,
    FrequencyDomainSingularityRefinementReason,
)
from klausurbotpro.application.frequency_domain_solution_report_renderer import (
    render_frequency_domain_solution_latex,
)
from klausurbotpro.application.frequency_domain_workflow_contracts import (
    FrequencyDomainWorkflowDiagnosticCode,
    FrequencyDomainWorkflowLimits,
    FrequencyDomainWorkflowMode,
    FrequencyDomainWorkflowRequest,
    FrequencyDomainWorkflowResult,
    FrequencyDomainWorkflowStage,
    FrequencyDomainWorkflowStageRecord,
    FrequencyDomainWorkflowStageStatus,
    FrequencyDomainWorkflowStatus,
    FrequencyPhasePresentation,
)
from klausurbotpro.application.frequency_domain_workflow_service import (
    FrequencyDomainWorkflowService,
)
from klausurbotpro.application.frequency_table_projection import (
    COMPACT_FREQUENCY_TABLE_TARGET_SIZE,
    FrequencyTableScope,
    select_frequency_table_indices,
)
from klausurbotpro.application.latex_task_heading import prepend_latex_task_heading
from klausurbotpro.application.standard_element_bode_formatting import (
    exact_expression_decimal_text,
    standard_element_asymptote_plain,
    standard_element_decomposition_plain,
    standard_element_events_plain,
)
from klausurbotpro.application.state_space_workflow import (
    preview_matrix_dimensions,
    preview_structured_ode,
    run_state_space_workflow,
)
from klausurbotpro.application.time_domain_workflow import (
    TimeDomainInputDraft,
    TimeDomainPresentation,
    TimeDomainWorkflowResult,
    run_time_domain_workflow,
)
from klausurbotpro.application.transfer_function_preparation_contracts import (
    TransferFunctionPreparationResult,
    TransferFunctionPreparationStage,
    TransferFunctionPreparationStageRecord,
    TransferFunctionPreparationStageStatus,
    TransferFunctionPreparationStatus,
)
from klausurbotpro.application.transfer_function_preparation_service import (
    TransferFunctionPreparationService,
)
from klausurbotpro.application.transfer_function_request_factory import (
    ParameterInputDraft,
    TransferFunctionInputDraft,
    TransferFunctionRequestCreationResult,
    TransferFunctionRequestFactory,
    TransferFunctionRequestFieldError,
)
from klausurbotpro.application.transfer_function_solution_report_builder import (
    TransferFunctionSolutionReportBuilder,
)
from klausurbotpro.application.transfer_function_solution_report_contracts import (
    ConditionLine,
    EquationLine,
    OverrideLine,
    ReportDiagnostic,
    ReportDiagnosticCode,
    ReportMathExpression,
    ResultLine,
    SolutionLine,
    SolutionReportLimits,
    SolutionReportStatus,
    SolutionSection,
    SolutionSectionKind,
    SolutionSectionStatus,
    SourceReferenceLine,
    TransferFunctionExpressionPair,
    TransferFunctionSolutionReport,
    TransformationLine,
    WarningLine,
)
from klausurbotpro.application.transfer_function_solution_report_renderers import (
    render_solution_report_latex,
    render_solution_report_plaintext,
)
from klausurbotpro.application.transfer_function_workflow_contracts import (
    OverrideProvenance,
    RawTransferFunctionOverride,
    ReducedTransferFunctionOverride,
    RootAnalysisOverride,
    TransferFunctionWorkflowLimits,
    TransferFunctionWorkflowOverride,
    TransferFunctionWorkflowRequest,
    TransferFunctionWorkflowState,
    WorkflowDiagnosticCode,
    WorkflowDiagnosticEntry,
    WorkflowInputForm,
    WorkflowOverrideOriginKind,
    WorkflowStage,
    WorkflowStageRecord,
    WorkflowStageStatus,
    WorkflowValueOrigin,
)
from klausurbotpro.application.transfer_function_workflow_service import (
    TransferFunctionWorkflowService,
)
from klausurbotpro.domain.hurwitz_contracts import HurwitzAnalysisResult
from klausurbotpro.domain.routh_contracts import RouthDegreeCaseResult
from klausurbotpro.domain.standard_element_bode_contributions import (
    BodeSketchMode,
    standard_element_contributions,
)
from klausurbotpro.domain.state_space_contracts import (
    ExactMatrix,
    StateSpaceAnalysisResult,
    StateSpaceAnalysisTarget,
    StateSpaceCheck,
    StateSpaceInputDraft,
    StateSpaceModel,
    StateSpaceRealPartCheck,
    StateSpaceStatus,
    StateSpaceTaskType,
)
from klausurbotpro.domain.time_domain_contracts import (
    InputSignalType,
    OdeAnalysisGoal,
    TimeDomainTaskType,
)

__all__ = [
    "BodeSketchMode",
    "ControllerDesignCandidate",
    "ControllerDesignCandidateStatus",
    "ControllerDesignInputDraft",
    "ControllerDesignMethod",
    "ControllerDesignOutcomeDecision",
    "ControllerDesignResult",
    "ControllerType",
    "ControllerDesignWorkflowService",
    "controller_design_candidate_status_text",
    "controller_design_method_text",
    "decide_p_phase_margin_outcome",
    "exact_expression_decimal_text",
    "ExactMatrix",
    "ConditionLine",
    "EquationLine",
    "FrequencyDomainWorkflowDiagnosticCode",
    "FrequencyDomainInputDraft",
    "FrequencyDomainRequestCreationResult",
    "FrequencyDomainRequestFactory",
    "FrequencyDomainRequestFieldError",
    "FrequencyDomainSingularityRefinementPlan",
    "FrequencyDomainSingularityRefinementPlanner",
    "FrequencyDomainSingularityRefinementReason",
    "FrequencyDomainWorkflowLimits",
    "FrequencyDomainWorkflowMode",
    "FrequencyDomainWorkflowRequest",
    "FrequencyDomainWorkflowResult",
    "FrequencyDomainWorkflowService",
    "FrequencyDomainWorkflowStage",
    "FrequencyDomainWorkflowStageRecord",
    "FrequencyDomainWorkflowStageStatus",
    "FrequencyDomainWorkflowStatus",
    "FrequencyPhasePresentation",
    "FrequencyTableScope",
    "HurwitzAnalysisResult",
    "OverrideProvenance",
    "OverrideLine",
    "ParameterInputDraft",
    "prepend_latex_task_heading",
    "RawTransferFunctionOverride",
    "ReducedTransferFunctionOverride",
    "ReportDiagnostic",
    "ReportDiagnosticCode",
    "ReportMathExpression",
    "ResultLine",
    "RootAnalysisOverride",
    "RouthDegreeCaseResult",
    "SolutionLine",
    "SolutionReportLimits",
    "SolutionReportStatus",
    "SolutionSection",
    "SolutionSectionKind",
    "SolutionSectionStatus",
    "SourceReferenceLine",
    "standard_element_asymptote_plain",
    "standard_element_decomposition_plain",
    "standard_element_events_plain",
    "standard_element_contributions",
    "TransferFunctionExpressionPair",
    "TransferFunctionInputDraft",
    "TransferFunctionPreparationResult",
    "TransferFunctionPreparationService",
    "TransferFunctionPreparationStage",
    "TransferFunctionPreparationStageRecord",
    "TransferFunctionPreparationStageStatus",
    "TransferFunctionPreparationStatus",
    "TransferFunctionRequestCreationResult",
    "TransferFunctionRequestFactory",
    "TransferFunctionRequestFieldError",
    "TransferFunctionSolutionReport",
    "TransferFunctionSolutionReportBuilder",
    "TransferFunctionWorkflowLimits",
    "TransferFunctionWorkflowOverride",
    "TransferFunctionWorkflowRequest",
    "TransferFunctionWorkflowService",
    "TransferFunctionWorkflowState",
    "WorkflowDiagnosticCode",
    "WorkflowDiagnosticEntry",
    "WorkflowInputForm",
    "WorkflowOverrideOriginKind",
    "WorkflowStage",
    "WorkflowStageRecord",
    "WorkflowStageStatus",
    "WorkflowValueOrigin",
    "TransformationLine",
    "TimeDomainInputDraft",
    "InputSignalType",
    "OdeAnalysisGoal",
    "TimeDomainPresentation",
    "TimeDomainTaskType",
    "TimeDomainWorkflowResult",
    "WarningLine",
    "render_solution_report_latex",
    "render_solution_report_plaintext",
    "render_frequency_domain_solution_latex",
    "select_frequency_table_indices",
    "COMPACT_FREQUENCY_TABLE_TARGET_SIZE",
    "run_time_domain_workflow",
    "StateSpaceAnalysisResult",
    "StateSpaceAnalysisTarget",
    "StateSpaceCheck",
    "StateSpaceInputDraft",
    "StateSpaceModel",
    "StateSpaceRealPartCheck",
    "StateSpaceStatus",
    "StateSpaceTaskType",
    "preview_matrix_dimensions",
    "preview_structured_ode",
    "run_state_space_workflow",
]
